### ISSUE TITLE
Deprecate has?

### ISSUE THREAD

**Issue by RDIL** [tarruda/has#19]
Since this module is so tiny, and TC39 has (I believe) standardized `Object.hasOwn`, it makes sense to deprecate this package.  Are there any plans or thoughts from anyone about this idea?

Just opening this issue as a suggestion, since I personally think this makes sense, but if the maintainers disagree, that’s fine.

**Comment by ljharb** [comment]
There will always be engines that don’t have Object.hasOwn, and supporting old engines is very important, so i don’t see the sense of deprecating this for the foreseeable future.

**Comment by jjangga0214** [comment]
@ljharb I know you're an expert on nodejs ecosystem. But in general, "deprecation" means a package or the package's certain feature is replaced by a new one. So users can replace it with the new one if possible, or stick with the old one if they can't (or don't want). Possible reasons they can't change include that they depend on another old environment(in this case, old engine) which can't work with the new one.

Doesn't this situation fit with the concept of deprecation?

**Comment by ljharb** [comment]
@jjangga0214 Deprecation is when there's another viable replacement package. The only alternative for this one is an Object.hasOwn polyfill. I also maintain https://npmjs.com/object.hasown, but I still don't think this one should be deprecated in favor of that one.

I do not believe the concept of deprecation applies here, no.
