### ISSUE TITLE
Remove function-bind

### ISSUE THREAD

**Issue by stevenvachon** [tarruda/has#8]
Node 4.x has no need for it and if our browser projects need to support very old versions, we can include a polyfill ourselves.

**Comment by tarruda** [comment]
The idea of this module is to be a quick shortcut that just works, and function-bind already uses `Function.prototype.bind` if available so there's no need to remove it.

If you don't need to support legacy environments and wan to optimize your js bundle as much as possible, it is easy to provide the implementation yourself with browserify `-r` command-line option: `browserify -r /path/to/your/has.js:has`. (and every module that depends on `has` will use your version instead)
